export const quranNarrations = [
  {
    ar: "حفص عن عاصم",
    en: "Hafs from Asim",
    db:"Hafs_on_the_authority_of_Asim"
  },
  {
    ar: "ورش عن نافع",
    en: "Warsh from Nafi’",
    db:"Warsh_on_the_authority_of_Nafi"
  },
  {
    ar: "قالون عن نافع",
    en: "Qalun from Nafi’",
    db:"They_said_about_Nafi"
  },
  {
    ar: "الدوري عن أبي عمرو",
    en: "Al-Duri from Abu Amr",
    db:"Al_Duri_on_the_authority_of_Abu_Amr"
  },
  {
    ar: "الدوري عن الكسائي",
    en: "Al-Duri from Al-Kisa’i",
    db:"Al_Douri_from_Al_Kisa_i"
  },
  {
    ar: "شعبة عن عاصم",
    en: "Shu’bah from Asim",
    db:"Shu_bah_about_Asim"
  },
  {
    ar: "البزي عن ابن كثير",
    en: "Al-Bazzi from Ibn Kathir",
    db:"Al_Bazi_on_the_authority_of_Ibn_Kathir"
  },
  {
    ar: "قنبل عن ابن كثير",
    en: "Qunbul from Ibn Kathir",
    db:"Qunbil_on_the_authority_of_Ibn_Kathir"
  },
  {
    ar: "البزي وقنبل عن ابن كثير",
    en: "Al-Bazzi and Qunbul from Ibn Kathir",
    db:"Al_Bazi_and_Qunbul_on_the_authority_of_Ibn_Kathir"
  },
  {
    ar: "خلف عن حمزة",
    en: "Khalaf from Hamzah",
    db:"Khalaf_on_the_authority_of_Hamza"
  },
  {
    ar: "السوسي عن أبي عمرو",
    en: "Al-Susi from Abu Amr",
    db:"Al_Susi_on_the_authority_of_Abu_Amr"
  },
  {
    ar: "ابن ذكوان عن ابن عامر",
    en: "Ibn Dhakwan from Ibn Amir",
    db:"bn_Dhakwan_on_the_authority_of_Ibn_Amer",
  },
  {
    ar: "روايتي رويس وروح",
    en: "The narrations of Ruways and Rawh",
    db:"My_novel_Royce_and_Soul"
  }
]
export const quranSurahs  = {
  quarter_1: [
    { id: 1, ar: "الفاتحة", en: "Al-Fatihah" },
    { id: 2, ar: "البقرة", en: "Al-Baqarah" },
    { id: 3, ar: "آل عمران", en: "Al-Imran" },
    { id: 4, ar: "النساء", en: "An-Nisa" },
    { id: 5, ar: "المائدة", en: "Al-Ma'idah" },
    { id: 6, ar: "الأنعام", en: "Al-An'am" }
  ],
  quarter_2: [
    { id: 7, ar: "الأعراف", en: "Al-A'raf" },
    { id: 8, ar: "الأنفال", en: "Al-Anfal" },
    { id: 9, ar: "التوبة", en: "At-Tawbah" },
    { id: 10, ar: "يونس", en: "Yunus" },
    { id: 11, ar: "هود", en: "Hud" },
    { id: 12, ar: "يوسف", en: "Yusuf" },
    { id: 13, ar: "الرعد", en: "Ar-Ra'd" },
    { id: 14, ar: "إبراهيم", en: "Ibrahim" },
    { id: 15, ar: "الحجر", en: "Al-Hijr" },
    { id: 16, ar: "النحل", en: "An-Nahl" },
    { id: 17, ar: "الإسراء", en: "Al-Isra" },
    { id: 18, ar: "الكهف", en: "Al-Kahf" },        
  ],
  quarter_3: [
    { id: 19, ar: "مريم", en: "Maryam" },
    { id: 20, ar: "طه", en: "Taha" },
    { id: 21, ar: "الأنبياء", en: "Al-Anbiya" },
    { id: 22, ar: "الحج", en: "Al-Hajj" },
    { id: 23, ar: "المؤمنون", en: "Al-Mu'minun" },
    { id: 24, ar: "النور", en: "An-Nur" },
    { id: 25, ar: "الفرقان", en: "Al-Furqan" },
    { id: 26, ar: "الشعراء", en: "Ash-Shu'ara" },
    { id: 27, ar: "النمل", en: "An-Naml" },      
    { id: 28, ar: "القصص", en: "Al-Qasas" },  
    { id: 29, ar: "العنكبوت", en: "Al-Ankabut" },
    { id: 30, ar: "الروم", en: "Ar-Rum" },
    { id: 31, ar: "لقمان", en: "Luqman" },
    { id: 32, ar: "السجدة", en: "As-Sajdah" },
    { id: 33, ar: "الأحزاب", en: "Al-Ahzab" },
    { id: 34, ar: "سبأ", en: "Saba" },
    { id: 35, ar: "فاطر", en: "Fatir" },
    { id: 36, ar: "يس", en: "Ya-Sin" }
  ],
  quarter_4: [
    { id: 37, ar: "الصافات", en: "As-Saffat" },
    { id: 38, ar: "ص", en: "Sad" },
    { id: 39, ar: "الزمر", en: "Az-Zumar" },
    { id: 40, ar: "غافر", en: "Ghafir" },
    { id: 41, ar: "فصلت", en: "Fussilat" },
    { id: 42, ar: "الشورى", en: "Ash-Shura" },
    { id: 43, ar: "الزخرف", en: "Az-Zukhruf" },
    { id: 44, ar: "الدخان", en: "Ad-Dukhan" },
    { id: 45, ar: "الجاثية", en: "Al-Jathiyah" },
    { id: 46, ar: "الأحقاف", en: "Al-Ahqaf" },
    { id: 47, ar: "محمد", en: "Muhammad" },
    { id: 48, ar: "الفتح", en: "Al-Fath" },
    { id: 49, ar: "الحجرات", en: "Al-Hujurat" },
    { id: 50, ar: "ق", en: "Qaf" },
    { id: 51, ar: "الذاريات", en: "Adh-Dhariyat" },
    { id: 52, ar: "الطور", en: "At-Tur" },
    { id: 53, ar: "النجم", en: "An-Najm" },
    { id: 54, ar: "القمر", en: "Al-Qamar" },
    { id: 55, ar: "الرحمن", en: "Ar-Rahman" },
    { id: 56, ar: "الواقعة", en: "Al-Waqi'ah" },
    { id: 57, ar: "الحديد", en: "Al-Hadid" },
    { id: 58, ar: "المجادلة", en: "Al-Mujadilah" },
    { id: 59, ar: "الحشر", en: "Al-Hashr" },
    { id: 60, ar: "الممتحنة", en: "Al-Mumtahanah" },
    { id: 61, ar: "الصف", en: "As-Saff" },
    { id: 62, ar: "الجمعة", en: "Al-Jumu'ah" },
    { id: 63, ar: "المنافقون", en: "Al-Munafiqun" },
    { id: 64, ar: "التغابن", en: "At-Taghabun" },
    { id: 65, ar: "الطلاق", en: "At-Talaq" },
    { id: 66, ar: "التحريم", en: "At-Tahrim" },
    { id: 67, ar: "الملك", en: "Al-Mulk" },
    { id: 68, ar: "القلم", en: "Al-Qalam" },
    { id: 69, ar: "الحاقة", en: "Al-Haqqah" },
    { id: 70, ar: "المعارج", en: "Al-Ma'arij" },
    { id: 71, ar: "نوح", en: "Nuh" },
    { id: 72, ar: "الجن", en: "Al-Jinn" },
    { id: 73, ar: "المزمل", en: "Al-Muzzammil" },
    { id: 74, ar: "المدثر", en: "Al-Muddaththir" },
    { id: 75, ar: "القيامة", en: "Al-Qiyamah" },
    { id: 76, ar: "الإنسان", en: "Al-Insan" },
    { id: 77, ar: "المرسلات", en: "Al-Mursalat" },
    { id: 78, ar: "النبأ", en: "An-Naba" },
    { id: 79, ar: "النازعات", en: "An-Nazi'at" },
    { id: 80, ar: "عبس", en: "Abasa" },
    { id: 81, ar: "التكوير", en: "At-Takwir" },
    { id: 82, ar: "الانفطار", en: "Al-Infitar" },
    { id: 83, ar: "المطففين", en: "Al-Mutaffifin" },
    { id: 84, ar: "الانشقاق", en: "Al-Inshiqaq" },
    { id: 85, ar: "البروج", en: "Al-Buruj" },
    { id: 86, ar: "الطارق", en: "At-Tariq" },
    { id: 87, ar: "الأعلى", en: "Al-A'la" },
    { id: 88, ar: "الغاشية", en: "Al-Ghashiyah" },
    { id: 89, ar: "الفجر", en: "Al-Fajr" },
    { id: 90, ar: "البلد", en: "Al-Balad" },
    { id: 91, ar: "الشمس", en: "Ash-Shams" },
    { id: 92, ar: "الليل", en: "Al-Layl" },
    { id: 93, ar: "الضحى", en: "Ad-Duha" },
    { id: 94, ar: "الشرح", en: "Ash-Sharh" },
    { id: 95, ar: "التين", en: "At-Tin" },
    { id: 96, ar: "العلق", en: "Al-Alaq" },
    { id: 97, ar: "القدر", en: "Al-Qadr" },
    { id: 98, ar: "البينة", en: "Al-Bayyinah" },
    { id: 99, ar: "الزلزلة", en: "Az-Zalzalah" },
    { id: 100, ar: "العاديات", en: "Al-Adiyat" },
    { id: 101, ar: "القارعة", en: "Al-Qari'ah" },
    { id: 102, ar: "التكاثر", en: "At-Takathur" },
    { id: 103, ar: "العصر", en: "Al-Asr" },
    { id: 104, ar: "الهمزة", en: "Al-Humazah" },
    { id: 105, ar: "الفيل", en: "Al-Fil" },
    { id: 106, ar: "قريش", en: "Quraysh" },
    { id: 107, ar: "الماعون", en: "Al-Ma'un" },
    { id: 108, ar: "الكوثر", en: "Al-Kawthar" },
    { id: 109, ar: "الكافرون", en: "Al-Kafirun" },
    { id: 110, ar: "النصر", en: "An-Nasr" },
    { id: 111, ar: "المسد", en: "Al-Masad" },
    { id: 112, ar: "الإخلاص", en: "Al-Ikhlas" },
    { id: 113, ar: "الفلق", en: "Al-Falaq" },
    { id: 114, ar: "الناس", en: "An-Nas" }
  ],
};
export const quranSurahsArray  = 
[
    { id: 1, ar: "الفاتحة", en: "Al-Fatihah" },
    { id: 2, ar: "البقرة", en: "Al-Baqarah" },
    { id: 3, ar: "آل عمران", en: "Al-Imran" },
    { id: 4, ar: "النساء", en: "An-Nisa" },
    { id: 5, ar: "المائدة", en: "Al-Ma'idah" },
    { id: 6, ar: "الأنعام", en: "Al-An'am" },
    { id: 7, ar: "الأعراف", en: "Al-A'raf" },
    { id: 8, ar: "الأنفال", en: "Al-Anfal" },
    { id: 9, ar: "التوبة", en: "At-Tawbah" },
    { id: 10, ar: "يونس", en: "Yunus" },
    { id: 11, ar: "هود", en: "Hud" },
    { id: 12, ar: "يوسف", en: "Yusuf" },
    { id: 13, ar: "الرعد", en: "Ar-Ra'd" },
    { id: 14, ar: "إبراهيم", en: "Ibrahim" },
    { id: 15, ar: "الحجر", en: "Al-Hijr" },
    { id: 16, ar: "النحل", en: "An-Nahl" },
    { id: 17, ar: "الإسراء", en: "Al-Isra" },
    { id: 18, ar: "الكهف", en: "Al-Kahf" },
    { id: 19, ar: "مريم", en: "Maryam" },
    { id: 20, ar: "طه", en: "Taha" },
    { id: 21, ar: "الأنبياء", en: "Al-Anbiya" },
    { id: 22, ar: "الحج", en: "Al-Hajj" },
    { id: 23, ar: "المؤمنون", en: "Al-Mu'minun" },
    { id: 24, ar: "النور", en: "An-Nur" },
    { id: 25, ar: "الفرقان", en: "Al-Furqan" },
    { id: 26, ar: "الشعراء", en: "Ash-Shu'ara" },
    { id: 27, ar: "النمل", en: "An-Naml" },      
    { id: 28, ar: "القصص", en: "Al-Qasas" },  
    { id: 29, ar: "العنكبوت", en: "Al-Ankabut" },
    { id: 30, ar: "الروم", en: "Ar-Rum" },
    { id: 31, ar: "لقمان", en: "Luqman" },
    { id: 32, ar: "السجدة", en: "As-Sajdah" },
    { id: 33, ar: "الأحزاب", en: "Al-Ahzab" },
    { id: 34, ar: "سبأ", en: "Saba" },
    { id: 35, ar: "فاطر", en: "Fatir" },
    { id: 36, ar: "يس", en: "Ya-Sin" },
    { id: 37, ar: "الصافات", en: "As-Saffat" },
    { id: 38, ar: "ص", en: "Sad" },
    { id: 39, ar: "الزمر", en: "Az-Zumar" },
    { id: 40, ar: "غافر", en: "Ghafir" },
    { id: 41, ar: "فصلت", en: "Fussilat" },
    { id: 42, ar: "الشورى", en: "Ash-Shura" },
    { id: 43, ar: "الزخرف", en: "Az-Zukhruf" },
    { id: 44, ar: "الدخان", en: "Ad-Dukhan" },
    { id: 45, ar: "الجاثية", en: "Al-Jathiyah" },
    { id: 46, ar: "الأحقاف", en: "Al-Ahqaf" },
    { id: 47, ar: "محمد", en: "Muhammad" },
    { id: 48, ar: "الفتح", en: "Al-Fath" },
    { id: 49, ar: "الحجرات", en: "Al-Hujurat" },
    { id: 50, ar: "ق", en: "Qaf" },
    { id: 51, ar: "الذاريات", en: "Adh-Dhariyat" },
    { id: 52, ar: "الطور", en: "At-Tur" },
    { id: 53, ar: "النجم", en: "An-Najm" },
    { id: 54, ar: "القمر", en: "Al-Qamar" },
    { id: 55, ar: "الرحمن", en: "Ar-Rahman" },
    { id: 56, ar: "الواقعة", en: "Al-Waqi'ah" },
    { id: 57, ar: "الحديد", en: "Al-Hadid" },
    { id: 58, ar: "المجادلة", en: "Al-Mujadilah" },
    { id: 59, ar: "الحشر", en: "Al-Hashr" },
    { id: 60, ar: "الممتحنة", en: "Al-Mumtahanah" },
    { id: 61, ar: "الصف", en: "As-Saff" },
    { id: 62, ar: "الجمعة", en: "Al-Jumu'ah" },
    { id: 63, ar: "المنافقون", en: "Al-Munafiqun" },
    { id: 64, ar: "التغابن", en: "At-Taghabun" },
    { id: 65, ar: "الطلاق", en: "At-Talaq" },
    { id: 66, ar: "التحريم", en: "At-Tahrim" },
    { id: 67, ar: "الملك", en: "Al-Mulk" },
    { id: 68, ar: "القلم", en: "Al-Qalam" },
    { id: 69, ar: "الحاقة", en: "Al-Haqqah" },
    { id: 70, ar: "المعارج", en: "Al-Ma'arij" },
    { id: 71, ar: "نوح", en: "Nuh" },
    { id: 72, ar: "الجن", en: "Al-Jinn" },
    { id: 73, ar: "المزمل", en: "Al-Muzzammil" },
    { id: 74, ar: "المدثر", en: "Al-Muddaththir" },
    { id: 75, ar: "القيامة", en: "Al-Qiyamah" },
    { id: 76, ar: "الإنسان", en: "Al-Insan" },
    { id: 77, ar: "المرسلات", en: "Al-Mursalat" },
    { id: 78, ar: "النبأ", en: "An-Naba" },
    { id: 79, ar: "النازعات", en: "An-Nazi'at" },
    { id: 80, ar: "عبس", en: "Abasa" },
    { id: 81, ar: "التكوير", en: "At-Takwir" },
    { id: 82, ar: "الانفطار", en: "Al-Infitar" },
    { id: 83, ar: "المطففين", en: "Al-Mutaffifin" },
    { id: 84, ar: "الانشقاق", en: "Al-Inshiqaq" },
    { id: 85, ar: "البروج", en: "Al-Buruj" },
    { id: 86, ar: "الطارق", en: "At-Tariq" },
    { id: 87, ar: "الأعلى", en: "Al-A'la" },
    { id: 88, ar: "الغاشية", en: "Al-Ghashiyah" },
    { id: 89, ar: "الفجر", en: "Al-Fajr" },
    { id: 90, ar: "البلد", en: "Al-Balad" },
    { id: 91, ar: "الشمس", en: "Ash-Shams" },
    { id: 92, ar: "الليل", en: "Al-Layl" },
    { id: 93, ar: "الضحى", en: "Ad-Duha" },
    { id: 94, ar: "الشرح", en: "Ash-Sharh" },
    { id: 95, ar: "التين", en: "At-Tin" },
    { id: 96, ar: "العلق", en: "Al-Alaq" },
    { id: 97, ar: "القدر", en: "Al-Qadr" },
    { id: 98, ar: "البينة", en: "Al-Bayyinah" },
    { id: 99, ar: "الزلزلة", en: "Az-Zalzalah" },
    { id: 100, ar: "العاديات", en: "Al-Adiyat" },
    { id: 101, ar: "القارعة", en: "Al-Qari'ah" },
    { id: 102, ar: "التكاثر", en: "At-Takathur" },
    { id: 103, ar: "العصر", en: "Al-Asr" },
    { id: 104, ar: "الهمزة", en: "Al-Humazah" },
    { id: 105, ar: "الفيل", en: "Al-Fil" },
    { id: 106, ar: "قريش", en: "Quraysh" },
    { id: 107, ar: "الماعون", en: "Al-Ma'un" },
    { id: 108, ar: "الكوثر", en: "Al-Kawthar" },
    { id: 109, ar: "الكافرون", en: "Al-Kafirun" },
    { id: 110, ar: "النصر", en: "An-Nasr" },
    { id: 111, ar: "المسد", en: "Al-Masad" },
    { id: 112, ar: "الإخلاص", en: "Al-Ikhlas" },
    { id: 113, ar: "الفلق", en: "Al-Falaq" },
    { id: 114, ar: "الناس", en: "An-Nas" }
  ]
